name: My First Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show Date
        run: date
      - name: Show Folder
        run: pwd
      - name: List Files
        run: ls
      - name: Say Hi
        run: echo "Hi Wei!"
