name: Wei's Second Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - run: pwd
      - run: ls -la
      - run: cat README.md
      - run: git status
      - run: git branch
      - run: git log --oneline -5
